============================= test session starts ==============================
platform sunos5 -- Python $(PYTHON_VERSION).X -- $(PYTHON)
cachedir: .pytest_cache
rootdir: $(@D)
collecting ... collected 27 items

tests/test_async_cached_property.py::TestCachedProperty::test_cached_property PASSED
tests/test_async_cached_property.py::TestCachedProperty::test_none_cached_property PASSED
tests/test_async_cached_property.py::TestCachedProperty::test_reset_cached_property PASSED
tests/test_cached_property.py::TestCachedProperty::test_cached_property PASSED
tests/test_cached_property.py::TestCachedProperty::test_none_cached_property PASSED
tests/test_cached_property.py::TestCachedProperty::test_reset_cached_property PASSED
tests/test_cached_property.py::TestCachedProperty::test_set_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedProperty::test_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedProperty::test_none_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedProperty::test_reset_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedProperty::test_set_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedProperty::test_threads PASSED
tests/test_cached_property.py::TestCachedPropertyWithTTL::test_cached_property PASSED
tests/test_cached_property.py::TestCachedPropertyWithTTL::test_none_cached_property PASSED
tests/test_cached_property.py::TestCachedPropertyWithTTL::test_reset_cached_property PASSED
tests/test_cached_property.py::TestCachedPropertyWithTTL::test_set_cached_property PASSED
tests/test_cached_property.py::TestCachedPropertyWithTTL::test_ttl_expiry PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_none_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_reset_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_set_cached_property PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_threads PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_threads_ttl_expiry PASSED
tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_ttl_expiry PASSED
tests/test_coroutine_cached_property.py::TestCachedProperty::test_cached_property PASSED
tests/test_coroutine_cached_property.py::TestCachedProperty::test_none_cached_property PASSED
tests/test_coroutine_cached_property.py::TestCachedProperty::test_reset_cached_property PASSED

=============================== warnings summary ===============================
tests/test_cached_property.py::TestThreadedCachedProperty::test_threads
  $(PYTHON_DIR)/vendor-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-10
  
  Traceback (most recent call last):
    File "$(PYTHON_DIR)/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "$(PYTHON_DIR)/threading.py", line 917, in run
      self._target(*self._args, **self._kwargs)
  TypeError: 'int' object is not callable
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_threads
  $(PYTHON_DIR)/vendor-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-20
  
  Traceback (most recent call last):
    File "$(PYTHON_DIR)/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "$(PYTHON_DIR)/threading.py", line 917, in run
      self._target(*self._args, **self._kwargs)
  TypeError: 'int' object is not callable
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_cached_property.py::TestThreadedCachedPropertyWithTTL::test_threads_ttl_expiry
  $(PYTHON_DIR)/vendor-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-30
  
  Traceback (most recent call last):
    File "$(PYTHON_DIR)/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "$(PYTHON_DIR)/threading.py", line 917, in run
      self._target(*self._args, **self._kwargs)
  TypeError: 'int' object is not callable
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======== 27 passed, 3 warnings ========
