ECONNREFUSED is 111 on Linux, but 146 on illumos.

--- redis-py-5.2.1/tests/test_connection.py.orig
+++ redis-py-5.2.1/tests/test_connection.py
@@ -349,7 +349,7 @@
     with pytest.raises(ConnectionError) as e:
         redis = Redis(port=9999)
         redis.set("a", "b")
-    assert str(e.value) == "Error 111 connecting to localhost:9999. Connection refused."
+    assert str(e.value) == "Error 146 connecting to localhost:9999. Connection refused."
 
 
 def test_unix_socket_connection_failure():
--- redis-py-5.2.1/tests/test_asyncio/test_connection.py.orig
+++ redis-py-5.2.1/tests/test_asyncio/test_connection.py
@@ -534,7 +534,7 @@
     with pytest.raises(ConnectionError) as e:
         redis = Redis(host="127.0.0.1", port=9999)
         await redis.set("a", "b")
-    assert str(e.value).startswith("Error 111 connecting to 127.0.0.1:9999. Connect")
+    assert str(e.value).startswith("Error 146 connecting to 127.0.0.1:9999. Connect")
 
 
 async def test_unix_socket_connection_failure():
