--- pyopenssl-25.0.0/tests/test_ssl.py.orig
+++ pyopenssl-25.0.0/tests/test_ssl.py
@@ -2476,6 +2476,7 @@
         clientSSL.connect((loopback_address(port), port.getsockname()[1]))
         # XXX An assertion?  Or something?
 
+    @pytest.mark.skip(reason="usually fails: https://github.com/pyca/pyopenssl/issues/1192")
     def test_connect_ex(self) -> None:
         """
         If there is a connection error, `Connection.connect_ex` returns the
